apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admin-dashboard
  name: admin-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-dashboard
  template:
    metadata:
      labels: 
        app: admin-dashboard
    spec:
      containers:
      - name: admin-dashboard
        image: imhshekhar47/admin-dashboard:latest
        imagePullPolicy: IfNotPresent 
        ports: 
        - name: http
          containerPort: 3000


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin-dashboard
  name: admin-dashboard
spec:
  type: NodePort
  selector:
    app: admin-dashboard
  ports:
  - nodePort: 32001
    port: 3000
    protocol: TCP
    targetPort: 3000
        